# a11-specific vendor tree
PRODUCT_COPY_FILES += \
    device/htc/a11/prebuilt/bin/adsprpcd:/system/bin/adsprpcd \
    device/htc/a11/prebuilt/bin/akmd:/system/bin/akmd \
    device/htc/a11/prebuilt/bin/charging:/system/bin/charging \
    device/htc/a11/prebuilt/bin/hci_qcomm_init:/system/bin/hci_qcomm_init \
    device/htc/a11/prebuilt/bin/irsc_util:/system/bin/irsc_util \
    device/htc/a11/prebuilt/bin/mm-qcamera-daemon:/system/bin/mm-qcamera-daemon \
    device/htc/a11/prebuilt/bin/mpdecision:/system/bin/mpdecision \
    device/htc/a11/prebuilt/bin/qseecomd:/system/bin/qseecomd \
    device/htc/a11/prebuilt/bin/rmt_storage:/system/bin/rmt_storage \
    device/htc/a11/prebuilt/bin/thermal-engine:/system/bin/thermal-engine \
    device/htc/a11/prebuilt/bin/time_daemon:/system/bin/time_daemon \
    device/htc/a11/prebuilt/blobs/chl/bin/netmgrd:/system/blobs/chl/bin/netmgrd \
    device/htc/a11/prebuilt/blobs/chl/bin/qmuxd:/system/blobs/chl/bin/qmuxd \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libdiag.so:/system/blobs/chl/vendor/lib/libdiag.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libdsi_netctrl.so:/system/blobs/chl/vendor/lib/libdsi_netctrl.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libdsnetutils.so:/system/blobs/chl/vendor/lib/libdsnetutils.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libdsutils.so:/system/blobs/chl/vendor/lib/libdsutils.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libidl.so:/system/blobs/chl/vendor/lib/libidl.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libnetmgr.so:/system/blobs/chl/vendor/lib/libnetmgr.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libqcci_legacy.so:/system/blobs/chl/vendor/lib/libqcci_legacy.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libqdi.so:/system/blobs/chl/vendor/lib/libqdi.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libqdp.so:/system/blobs/chl/vendor/lib/libqdp.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libqmi.so:/system/blobs/chl/vendor/lib/libqmi.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libqmi_cci.so:/system/blobs/chl/vendor/lib/libqmi_cci.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libqmi_client_qmux.so:/system/blobs/chl/vendor/lib/libqmi_client_qmux.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libqmi_common_so.so:/system/blobs/chl/vendor/lib/libqmi_common_so.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libqmi_csi.so:/system/blobs/chl/vendor/lib/libqmi_csi.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libqmi_csvt_srvc.so:/system/blobs/chl/vendor/lib/libqmi_csvt_srvc.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libqmi_encdec.so:/system/blobs/chl/vendor/lib/libqmi_encdec.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libqmiservices.so:/system/blobs/chl/vendor/lib/libqmiservices.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libril-qc-qmi-1.so:/system/blobs/chl/vendor/lib/libril-qc-qmi-1.so \
    device/htc/a11/prebuilt/blobs/chl/vendor/lib/libril-qcril-hook-oem.so:/system/blobs/chl/vendor/lib/libril-qcril-hook-oem.so \
    device/htc/a11/prebuilt/blobs/gsm/bin/netmgrd:/system/blobs/gsm/bin/netmgrd \
    device/htc/a11/prebuilt/blobs/gsm/bin/qmuxd:/system/blobs/gsm/bin/qmuxd \
    device/htc/a11/prebuilt/blobs/gsm/bin/rild:/system/blobs/gsm/bin/rild \
    device/htc/a11/prebuilt/blobs/gsm/lib/libhtc_rilhook.so:/system/blobs/gsm/lib/libhtc_rilhook.so \
    device/htc/a11/prebuilt/blobs/gsm/lib/libril.so:/system/blobs/gsm/lib/libril.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libdiag.so:/system/blobs/gsm/vendor/lib/libdiag.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libdsi_netctrl.so:/system/blobs/gsm/vendor/lib/libdsi_netctrl.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libdsnetutils.so:/system/blobs/gsm/vendor/lib/libdsnetutils.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libdsutils.so:/system/blobs/gsm/vendor/lib/libdsutils.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libidl.so:/system/blobs/gsm/vendor/lib/libidl.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libnetmgr.so:/system/blobs/gsm/vendor/lib/libnetmgr.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libqcci_legacy.so:/system/blobs/gsm/vendor/lib/libqcci_legacy.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libqdi.so:/system/blobs/gsm/vendor/lib/libqdi.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libqdp.so:/system/blobs/gsm/vendor/lib/libqdp.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libqmi.so:/system/blobs/gsm/vendor/lib/libqmi.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libqmi_cci.so:/system/blobs/gsm/vendor/lib/libqmi_cci.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libqmi_client_qmux.so:/system/blobs/gsm/vendor/lib/libqmi_client_qmux.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libqmi_common_so.so:/system/blobs/gsm/vendor/lib/libqmi_common_so.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libqmi_csi.so:/system/blobs/gsm/vendor/lib/libqmi_csi.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libqmi_encdec.so:/system/blobs/gsm/vendor/lib/libqmi_encdec.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libqmiservices.so:/system/blobs/gsm/vendor/lib/libqmiservices.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libril-qc-qmi-1.so:/system/blobs/gsm/vendor/lib/libril-qc-qmi-1.so \
    device/htc/a11/prebuilt/blobs/gsm/vendor/lib/libril-qcril-hook-oem.so:/system/blobs/gsm/vendor/lib/libril-qcril-hook-oem.so \
    device/htc/a11/prebuilt/etc/Bluetooth_cal.acdb:/system/etc/Bluetooth_cal.acdb \
    device/htc/a11/prebuilt/etc/General_cal.acdb:/system/etc/General_cal.acdb \
    device/htc/a11/prebuilt/etc/Global_cal.acdb:/system/etc/Global_cal.acdb \
    device/htc/a11/prebuilt/etc/Handset_cal.acdb:/system/etc/Handset_cal.acdb \
    device/htc/a11/prebuilt/etc/Hdmi_cal.acdb:/system/etc/Hdmi_cal.acdb \
    device/htc/a11/prebuilt/etc/Headset_cal.acdb:/system/etc/Headset_cal.acdb \
    device/htc/a11/prebuilt/etc/Speaker_cal.acdb:/system/etc/Speaker_cal.acdb \
    device/htc/a11/prebuilt/etc/firmware/ILP0100_IPM_Code_out.bin:/system/etc/firmware/ILP0100_IPM_Code_out.bin \
    device/htc/a11/prebuilt/etc/firmware/ILP0100_IPM_Data_out.bin:/system/etc/firmware/ILP0100_IPM_Data_out.bin \
    device/htc/a11/prebuilt/etc/firmware/a225_pfp.fw:/system/etc/firmware/a225_pfp.fw \
    device/htc/a11/prebuilt/etc/firmware/a225_pm4.fw:/system/etc/firmware/a225_pm4.fw \
    device/htc/a11/prebuilt/etc/firmware/a225p5_pm4.fw:/system/etc/firmware/a225p5_pm4.fw \
    device/htc/a11/prebuilt/etc/firmware/a300_pfp.fw:/system/etc/firmware/a300_pfp.fw \
    device/htc/a11/prebuilt/etc/firmware/a300_pm4.fw:/system/etc/firmware/a300_pm4.fw \
    device/htc/a11/prebuilt/etc/firmware/a330_pfp.fw:/system/etc/firmware/a330_pfp.fw \
    device/htc/a11/prebuilt/etc/firmware/a330_pm4.fw:/system/etc/firmware/a330_pm4.fw \
    device/htc/a11/prebuilt/etc/firmware/cpp_firmware_v1_1_1.fw:/system/etc/firmware/cpp_firmware_v1_1_1.fw \
    device/htc/a11/prebuilt/etc/firmware/cpp_firmware_v1_1_6.fw:/system/etc/firmware/cpp_firmware_v1_1_6.fw \
    device/htc/a11/prebuilt/etc/firmware/cpp_firmware_v1_2_0.fw:/system/etc/firmware/cpp_firmware_v1_2_0.fw \
    device/htc/a11/prebuilt/etc/firmware/hcheck.b00:/system/etc/firmware/hcheck.b00 \
    device/htc/a11/prebuilt/etc/firmware/hcheck.b01:/system/etc/firmware/hcheck.b01 \
    device/htc/a11/prebuilt/etc/firmware/hcheck.b02:/system/etc/firmware/hcheck.b02 \
    device/htc/a11/prebuilt/etc/firmware/hcheck.b03:/system/etc/firmware/hcheck.b03 \
    device/htc/a11/prebuilt/etc/firmware/hcheck.mdt:/system/etc/firmware/hcheck.mdt \
    device/htc/a11/prebuilt/etc/firmware/leia_pfp_470.fw:/system/etc/firmware/leia_pfp_470.fw \
    device/htc/a11/prebuilt/etc/firmware/leia_pm4_470.fw:/system/etc/firmware/leia_pm4_470.fw \
    device/htc/a11/prebuilt/etc/firmware/lscbuffer_rev2.bin:/system/etc/firmware/lscbuffer_rev2.bin \
    device/htc/a11/prebuilt/etc/firmware/venus.b00:/system/etc/firmware/venus.b00 \
    device/htc/a11/prebuilt/etc/firmware/venus.b01:/system/etc/firmware/venus.b01 \
    device/htc/a11/prebuilt/etc/firmware/venus.b02:/system/etc/firmware/venus.b02 \
    device/htc/a11/prebuilt/etc/firmware/venus.b03:/system/etc/firmware/venus.b03 \
    device/htc/a11/prebuilt/etc/firmware/venus.b04:/system/etc/firmware/venus.b04 \
    device/htc/a11/prebuilt/etc/firmware/venus.mbn:/system/etc/firmware/venus.mbn \
    device/htc/a11/prebuilt/etc/firmware/venus.mdt:/system/etc/firmware/venus.mdt \
    device/htc/a11/prebuilt/etc/gps.conf:/system/etc/gps.conf \
    device/htc/a11/prebuilt/etc/tfa/Rec_Video.drc:/system/etc/tfa/Rec_Video.drc \
    device/htc/a11/prebuilt/etc/tfa/Rec_Video.eq:/system/etc/tfa/Rec_Video.eq \
    device/htc/a11/prebuilt/etc/tfa/Rec_Video.preset:/system/etc/tfa/Rec_Video.preset \
    device/htc/a11/prebuilt/etc/tfa/Rec_Video_l.drc:/system/etc/tfa/Rec_Video_l.drc \
    device/htc/a11/prebuilt/etc/tfa/Rec_Video_l.eq:/system/etc/tfa/Rec_Video_l.eq \
    device/htc/a11/prebuilt/etc/tfa/Rec_Video_l.preset:/system/etc/tfa/Rec_Video_l.preset \
    device/htc/a11/prebuilt/etc/tfa/fm.drc:/system/etc/tfa/fm.drc \
    device/htc/a11/prebuilt/etc/tfa/fm.eq:/system/etc/tfa/fm.eq \
    device/htc/a11/prebuilt/etc/tfa/fm.preset:/system/etc/tfa/fm.preset \
    device/htc/a11/prebuilt/etc/tfa/fm_l.drc:/system/etc/tfa/fm_l.drc \
    device/htc/a11/prebuilt/etc/tfa/fm_l.eq:/system/etc/tfa/fm_l.eq \
    device/htc/a11/prebuilt/etc/tfa/fm_l.preset:/system/etc/tfa/fm_l.preset \
    device/htc/a11/prebuilt/etc/tfa/playback.drc:/system/etc/tfa/playback.drc \
    device/htc/a11/prebuilt/etc/tfa/playback.eq:/system/etc/tfa/playback.eq \
    device/htc/a11/prebuilt/etc/tfa/playback.preset:/system/etc/tfa/playback.preset \
    device/htc/a11/prebuilt/etc/tfa/playbackMFG.config:/system/etc/tfa/playbackMFG.config \
    device/htc/a11/prebuilt/etc/tfa/playbackMFG.drc:/system/etc/tfa/playbackMFG.drc \
    device/htc/a11/prebuilt/etc/tfa/playbackMFG.eq:/system/etc/tfa/playbackMFG.eq \
    device/htc/a11/prebuilt/etc/tfa/playbackMFG.preset:/system/etc/tfa/playbackMFG.preset \
    device/htc/a11/prebuilt/etc/tfa/playbackMFG_l.config:/system/etc/tfa/playbackMFG_l.config \
    device/htc/a11/prebuilt/etc/tfa/playbackMFG_l.drc:/system/etc/tfa/playbackMFG_l.drc \
    device/htc/a11/prebuilt/etc/tfa/playbackMFG_l.eq:/system/etc/tfa/playbackMFG_l.eq \
    device/htc/a11/prebuilt/etc/tfa/playbackMFG_l.preset:/system/etc/tfa/playbackMFG_l.preset \
    device/htc/a11/prebuilt/etc/tfa/playback_l.drc:/system/etc/tfa/playback_l.drc \
    device/htc/a11/prebuilt/etc/tfa/playback_l.eq:/system/etc/tfa/playback_l.eq \
    device/htc/a11/prebuilt/etc/tfa/playback_l.preset:/system/etc/tfa/playback_l.preset \
    device/htc/a11/prebuilt/etc/tfa/playbackwoofer.drc:/system/etc/tfa/playbackwoofer.drc \
    device/htc/a11/prebuilt/etc/tfa/playbackwoofer.eq:/system/etc/tfa/playbackwoofer.eq \
    device/htc/a11/prebuilt/etc/tfa/playbackwoofer.preset:/system/etc/tfa/playbackwoofer.preset \
    device/htc/a11/prebuilt/etc/tfa/playbackwoofer_l.drc:/system/etc/tfa/playbackwoofer_l.drc \
    device/htc/a11/prebuilt/etc/tfa/playbackwoofer_l.eq:/system/etc/tfa/playbackwoofer_l.eq \
    device/htc/a11/prebuilt/etc/tfa/playbackwoofer_l.preset:/system/etc/tfa/playbackwoofer_l.preset \
    device/htc/a11/prebuilt/etc/tfa/tfa9895.config:/system/etc/tfa/tfa9895.config \
    device/htc/a11/prebuilt/etc/tfa/tfa9895.patch:/system/etc/tfa/tfa9895.patch \
    device/htc/a11/prebuilt/etc/tfa/tfa9895.speaker:/system/etc/tfa/tfa9895.speaker \
    device/htc/a11/prebuilt/etc/tfa/tfa9895MFG.patch:/system/etc/tfa/tfa9895MFG.patch \
    device/htc/a11/prebuilt/etc/tfa/tfa9895_l.speaker:/system/etc/tfa/tfa9895_l.speaker \
    device/htc/a11/prebuilt/etc/tfa/voice.drc:/system/etc/tfa/voice.drc \
    device/htc/a11/prebuilt/etc/tfa/voice.eq:/system/etc/tfa/voice.eq \
    device/htc/a11/prebuilt/etc/tfa/voice.preset:/system/etc/tfa/voice.preset \
    device/htc/a11/prebuilt/etc/tfa/voiceWB.eq:/system/etc/tfa/voiceWB.eq \
    device/htc/a11/prebuilt/etc/tfa/voiceWB_l.eq:/system/etc/tfa/voiceWB_l.eq \
    device/htc/a11/prebuilt/etc/tfa/voice_l.drc:/system/etc/tfa/voice_l.drc \
    device/htc/a11/prebuilt/etc/tfa/voice_l.eq:/system/etc/tfa/voice_l.eq \
    device/htc/a11/prebuilt/etc/tfa/voice_l.preset:/system/etc/tfa/voice_l.preset \
    device/htc/a11/prebuilt/etc/tfa/voip.drc:/system/etc/tfa/voip.drc \
    device/htc/a11/prebuilt/etc/tfa/voip.eq:/system/etc/tfa/voip.eq \
    device/htc/a11/prebuilt/etc/tfa/voip.preset:/system/etc/tfa/voip.preset \
    device/htc/a11/prebuilt/etc/tfa/voip_l.drc:/system/etc/tfa/voip_l.drc \
    device/htc/a11/prebuilt/etc/tfa/voip_l.eq:/system/etc/tfa/voip_l.eq \
    device/htc/a11/prebuilt/etc/tfa/voip_l.preset:/system/etc/tfa/voip_l.preset \
    device/htc/a11/prebuilt/lib/hw/camera.vendor.msm8226.so:/system/lib/hw/camera.vendor.msm8226.so \
    device/htc/a11/prebuilt/lib/hw/gps.default.so:/system/lib/hw/gps.default.so \
    device/htc/a11/prebuilt/lib/hw/sensors.msm8226.so:/system/lib/hw/sensors.msm8226.so \
    device/htc/a11/prebuilt/lib/libgps.utils.so:/system/lib/libgps.utils.so \
    device/htc/a11/prebuilt/lib/libloc_api_v02.so:/system/lib/libloc_api_v02.so \
    device/htc/a11/prebuilt/lib/libloc_core.so:/system/lib/libloc_core.so \
    device/htc/a11/prebuilt/lib/libloc_ds_api.so:/system/lib/libloc_ds_api.so \
    device/htc/a11/prebuilt/lib/libloc_eng.so:/system/lib/libloc_eng.so \
    device/htc/a11/prebuilt/lib/libmmjpeg_interface.so:/system/lib/libmmjpeg_interface.so \
    device/htc/a11/prebuilt/vendor/firmware/cmnlib.b00:/system/vendor/firmware/cmnlib.b00 \
    device/htc/a11/prebuilt/vendor/firmware/cmnlib.b01:/system/vendor/firmware/cmnlib.b01 \
    device/htc/a11/prebuilt/vendor/firmware/cmnlib.b02:/system/vendor/firmware/cmnlib.b02 \
    device/htc/a11/prebuilt/vendor/firmware/cmnlib.b03:/system/vendor/firmware/cmnlib.b03 \
    device/htc/a11/prebuilt/vendor/firmware/cmnlib.mdt:/system/vendor/firmware/cmnlib.mdt \
    device/htc/a11/prebuilt/vendor/firmware/keymaster/keymaster.b00:/system/vendor/firmware/keymaster/keymaster.b00 \
    device/htc/a11/prebuilt/vendor/firmware/keymaster/keymaster.b01:/system/vendor/firmware/keymaster/keymaster.b01 \
    device/htc/a11/prebuilt/vendor/firmware/keymaster/keymaster.b02:/system/vendor/firmware/keymaster/keymaster.b02 \
    device/htc/a11/prebuilt/vendor/firmware/keymaster/keymaster.b03:/system/vendor/firmware/keymaster/keymaster.b03 \
    device/htc/a11/prebuilt/vendor/firmware/keymaster/keymaster.mdt:/system/vendor/firmware/keymaster/keymaster.mdt \
    device/htc/a11/prebuilt/vendor/firmware/libpn547_fw.so:/system/vendor/firmware/libpn547_fw.so \
    device/htc/a11/prebuilt/vendor/lib/egl/eglsubAndroid.so:/system/vendor/lib/egl/eglsubAndroid.so \
    device/htc/a11/prebuilt/vendor/lib/egl/libEGL_adreno.so:/system/vendor/lib/egl/libEGL_adreno.so \
    device/htc/a11/prebuilt/vendor/lib/egl/libGLESv1_CM_adreno.so:/system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    device/htc/a11/prebuilt/vendor/lib/egl/libGLESv2_adreno.so:/system/vendor/lib/egl/libGLESv2_adreno.so \
    device/htc/a11/prebuilt/vendor/lib/egl/libq3dtools_adreno.so:/system/vendor/lib/egl/libq3dtools_adreno.so \
    device/htc/a11/prebuilt/vendor/lib/libBeautyChat.so:/system/vendor/lib/libBeautyChat.so \
    device/htc/a11/prebuilt/vendor/lib/libC2D2.so:/system/vendor/lib/libC2D2.so \
    device/htc/a11/prebuilt/vendor/lib/libCB.so:/system/vendor/lib/libCB.so \
    device/htc/a11/prebuilt/vendor/lib/libI420colorconvert.so:/system/vendor/lib/libI420colorconvert.so \
    device/htc/a11/prebuilt/vendor/lib/libOpenCL.so:/system/vendor/lib/libOpenCL.so \
    device/htc/a11/prebuilt/vendor/lib/libOpenVG.so:/system/vendor/lib/libOpenVG.so \
    device/htc/a11/prebuilt/vendor/lib/libQSEEComAPI.so:/system/vendor/lib/libQSEEComAPI.so \
    device/htc/a11/prebuilt/vendor/lib/libRSDriver_adreno.so:/system/vendor/lib/libRSDriver_adreno.so \
    device/htc/a11/prebuilt/vendor/lib/libWVStreamControlAPI_L3.so:/system/vendor/lib/libWVStreamControlAPI_L3.so \
    device/htc/a11/prebuilt/vendor/lib/libacdbloader.so:/system/vendor/lib/libacdbloader.so \
    device/htc/a11/prebuilt/vendor/lib/libacdbmapper.so:/system/vendor/lib/libacdbmapper.so \
    device/htc/a11/prebuilt/vendor/lib/libacdbrtac.so:/system/vendor/lib/libacdbrtac.so \
    device/htc/a11/prebuilt/vendor/lib/libadiertac.so:/system/vendor/lib/libadiertac.so \
    device/htc/a11/prebuilt/vendor/lib/libadreno_utils.so:/system/vendor/lib/libadreno_utils.so \
    device/htc/a11/prebuilt/vendor/lib/libadsprpc.so:/system/vendor/lib/libadsprpc.so \
    device/htc/a11/prebuilt/vendor/lib/libaudcal.so:/system/vendor/lib/libaudcal.so \
    device/htc/a11/prebuilt/vendor/lib/libawb_calibration.so:/system/vendor/lib/libawb_calibration.so \
    device/htc/a11/prebuilt/vendor/lib/libc2d30-a3xx.so:/system/vendor/lib/libc2d30-a3xx.so \
    device/htc/a11/prebuilt/vendor/lib/libc2d30.so:/system/vendor/lib/libc2d30.so \
    device/htc/a11/prebuilt/vendor/lib/libcamera_aec.so:/system/vendor/lib/libcamera_aec.so \
    device/htc/a11/prebuilt/vendor/lib/libcamera_af.so:/system/vendor/lib/libcamera_af.so \
    device/htc/a11/prebuilt/vendor/lib/libcamera_awb.so:/system/vendor/lib/libcamera_awb.so \
    device/htc/a11/prebuilt/vendor/lib/libcameraface.so:/system/vendor/lib/libcameraface.so \
    device/htc/a11/prebuilt/vendor/lib/libcamerapp.so:/system/vendor/lib/libcamerapp.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so:/system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so:/system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so:/system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so:/system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so:/system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so:/system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so:/system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so:/system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so:/system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so:/system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so:/system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so:/system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so:/system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov13850_common.so:/system/vendor/lib/libchromatix_ov13850_common.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov13850_default_video.so:/system/vendor/lib/libchromatix_ov13850_default_video.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov13850_hdr.so:/system/vendor/lib/libchromatix_ov13850_hdr.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov13850_hfr.so:/system/vendor/lib/libchromatix_ov13850_hfr.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov13850_hfr_60fps.so:/system/vendor/lib/libchromatix_ov13850_hfr_60fps.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov13850_preview.so:/system/vendor/lib/libchromatix_ov13850_preview.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov13850_qtr.so:/system/vendor/lib/libchromatix_ov13850_qtr.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov13850_zoe.so:/system/vendor/lib/libchromatix_ov13850_zoe.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov5648_oty5f03_common.so:/system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:/system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:/system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:/system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov8865_q8v18a_common.so:/system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:/system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:/system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:/system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:/system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:/system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:/system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:/system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:/system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:/system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_s5k5e_onelane_common.so:/system/vendor/lib/libchromatix_s5k5e_onelane_common.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_s5k5e_onelane_default_video.so:/system/vendor/lib/libchromatix_s5k5e_onelane_default_video.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_s5k5e_onelane_hdr.so:/system/vendor/lib/libchromatix_s5k5e_onelane_hdr.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_s5k5e_onelane_preview.so:/system/vendor/lib/libchromatix_s5k5e_onelane_preview.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_s5k5e_onelane_video_16_9.so:/system/vendor/lib/libchromatix_s5k5e_onelane_video_16_9.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so:/system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so:/system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so:/system/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so:/system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so:/system/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so:/system/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so:/system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so:/system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so:/system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so:/system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so:/system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so:/system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so:/system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so:/system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so:/system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so:/system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so:/system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so:/system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so \
    device/htc/a11/prebuilt/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so:/system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so \
    device/htc/a11/prebuilt/vendor/lib/libfastcvadsp_stub.so:/system/vendor/lib/libfastcvadsp_stub.so \
    device/htc/a11/prebuilt/vendor/lib/libfastcvopt.so:/system/vendor/lib/libfastcvopt.so \
    device/htc/a11/prebuilt/vendor/lib/libfastcvopt.so:/system/vendor/lib/libfastcvopt.so \
    device/htc/a11/prebuilt/vendor/lib/libgeofence.so:/system/vendor/lib/libgeofence.so \
    device/htc/a11/prebuilt/vendor/lib/libgsl.so:/system/vendor/lib/libgsl.so \
    device/htc/a11/prebuilt/vendor/lib/libhtccamera.so:/system/vendor/lib/libhtccamera.so \
    device/htc/a11/prebuilt/vendor/lib/libizat_core.so:/system/vendor/lib/libizat_core.so \
    device/htc/a11/prebuilt/vendor/lib/libjpegdhw.so:/system/vendor/lib/libjpegdhw.so \
    device/htc/a11/prebuilt/vendor/lib/libjpegehw.so:/system/vendor/lib/libjpegehw.so \
    device/htc/a11/prebuilt/vendor/lib/liblbs_core.so:/system/vendor/lib/liblbs_core.so \
    device/htc/a11/prebuilt/vendor/lib/libllvm-qcom.so:/system/vendor/lib/libllvm-qcom.so \
    device/htc/a11/prebuilt/vendor/lib/libmm-color-convertor.so:/system/vendor/lib/libmm-color-convertor.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera2_c2d_module.so:/system/vendor/lib/libmmcamera2_c2d_module.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera2_cpp_module.so:/system/vendor/lib/libmmcamera2_cpp_module.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera2_iface_modules.so:/system/vendor/lib/libmmcamera2_iface_modules.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera2_imglib_modules.so:/system/vendor/lib/libmmcamera2_imglib_modules.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera2_isp_modules.so:/system/vendor/lib/libmmcamera2_isp_modules.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera2_pproc_modules.so:/system/vendor/lib/libmmcamera2_pproc_modules.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera2_sensor_modules.so:/system/vendor/lib/libmmcamera2_sensor_modules.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera2_stats_algorithm.so:/system/vendor/lib/libmmcamera2_stats_algorithm.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera2_stats_modules.so:/system/vendor/lib/libmmcamera2_stats_modules.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera2_vpe_module.so:/system/vendor/lib/libmmcamera2_vpe_module.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera2_wnr_module.so:/system/vendor/lib/libmmcamera2_wnr_module.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:/system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:/system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_faceproc.so:/system/vendor/lib/libmmcamera_faceproc.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_hdr_gb_lib.so:/system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_hdr_lib.so:/system/vendor/lib/libmmcamera_hdr_lib.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_imglib.so:/system/vendor/lib/libmmcamera_imglib.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_interface.so:/system/vendor/lib/libmmcamera_interface.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:/system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_ov13850.so:/system/vendor/lib/libmmcamera_ov13850.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_ov5648_oty5f03.so:/system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_ov8865_q8v18a.so:/system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_s5k5e_onelane.so:/system/vendor/lib/libmmcamera_s5k5e_onelane.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so:/system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:/system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:/system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_sp1628.so:/system/vendor/lib/libmmcamera_sp1628.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:/system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:/system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:/system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_tintless_algo.so:/system/vendor/lib/libmmcamera_tintless_algo.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:/system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:/system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_tuning.so:/system/vendor/lib/libmmcamera_tuning.so \
    device/htc/a11/prebuilt/vendor/lib/libmmcamera_wavelet_lib.so:/system/vendor/lib/libmmcamera_wavelet_lib.so \
    device/htc/a11/prebuilt/vendor/lib/libmmipl.so:/system/vendor/lib/libmmipl.so \
    device/htc/a11/prebuilt/vendor/lib/libmmjpeg.so:/system/vendor/lib/libmmjpeg.so \
    device/htc/a11/prebuilt/vendor/lib/libmmqjpeg_codec.so:/system/vendor/lib/libmmqjpeg_codec.so \
    device/htc/a11/prebuilt/vendor/lib/liboemcamera.so:/system/vendor/lib/liboemcamera.so \
    device/htc/a11/prebuilt/vendor/lib/libposteffect.so:/system/vendor/lib/libposteffect.so \
    device/htc/a11/prebuilt/vendor/lib/libqc-opt.so:/system/vendor/lib/libqc-opt.so \
    device/htc/a11/prebuilt/vendor/lib/libqomx_core.so:/system/vendor/lib/libqomx_core.so \
    device/htc/a11/prebuilt/vendor/lib/libqomx_jpegdec.so:/system/vendor/lib/libqomx_jpegdec.so \
    device/htc/a11/prebuilt/vendor/lib/libqomx_jpegenc.so:/system/vendor/lib/libqomx_jpegenc.so \
    device/htc/a11/prebuilt/vendor/lib/librs_adreno.so:/system/vendor/lib/librs_adreno.so \
    device/htc/a11/prebuilt/vendor/lib/librs_adreno_sha1.so:/system/vendor/lib/librs_adreno_sha1.so \
    device/htc/a11/prebuilt/vendor/lib/libsc-a3xx.so:/system/vendor/lib/libsc-a3xx.so \
    device/htc/a11/prebuilt/vendor/lib/libthermalclient.so:/system/vendor/lib/libthermalclient.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec.so:/system/vendor/lib/libtuning_aec.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_ov13850_hdr.so:/system/vendor/lib/libtuning_aec_ov13850_hdr.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_ov13850_hdr_16_9.so:/system/vendor/lib/libtuning_aec_ov13850_hdr_16_9.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_ov13850_night.so:/system/vendor/lib/libtuning_aec_ov13850_night.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_ov13850_night_16_9.so:/system/vendor/lib/libtuning_aec_ov13850_night_16_9.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_ov13850_video.so:/system/vendor/lib/libtuning_aec_ov13850_video.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_ov13850_videoHFR.so:/system/vendor/lib/libtuning_aec_ov13850_videoHFR.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_ov13850_video_60fps.so:/system/vendor/lib/libtuning_aec_ov13850_video_60fps.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_ov13850_zoe.so:/system/vendor/lib/libtuning_aec_ov13850_zoe.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_ov13850_zsl.so:/system/vendor/lib/libtuning_aec_ov13850_zsl.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_ov13850_zsl_16_9.so:/system/vendor/lib/libtuning_aec_ov13850_zsl_16_9.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_s5k5e_onelane_hdr.so:/system/vendor/lib/libtuning_aec_s5k5e_onelane_hdr.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_s5k5e_onelane_hdr_16_9.so:/system/vendor/lib/libtuning_aec_s5k5e_onelane_hdr_16_9.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_s5k5e_onelane_video.so:/system/vendor/lib/libtuning_aec_s5k5e_onelane_video.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_s5k5e_onelane_video_16_9.so:/system/vendor/lib/libtuning_aec_s5k5e_onelane_video_16_9.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_s5k5e_onelane_zsl.so:/system/vendor/lib/libtuning_aec_s5k5e_onelane_zsl.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_aec_s5k5e_onelane_zsl_16_9.so:/system/vendor/lib/libtuning_aec_s5k5e_onelane_zsl_16_9.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_af.so:/system/vendor/lib/libtuning_af.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_af_0.so:/system/vendor/lib/libtuning_af_0.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_af_1.so:/system/vendor/lib/libtuning_af_1.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_af_3.so:/system/vendor/lib/libtuning_af_3.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_awb_ov13850.so:/system/vendor/lib/libtuning_awb_ov13850.so \
    device/htc/a11/prebuilt/vendor/lib/libtuning_awb_s5k5e_onelane.so:/system/vendor/lib/libtuning_awb_s5k5e_onelane.so \
    device/htc/a11/prebuilt/vendor/lib/libwvm.so:/system/vendor/lib/libwvm.so \
    device/htc/a11/prebuilt/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so:/system/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so \
    device/htc/a11/prebuilt/vendor/lib/rfsa/adsp/libdspCV_skel.so:/system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
    device/htc/a11/prebuilt/vendor/lib/rfsa/adsp/libfastcvadsp.so:/system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
    device/htc/a11/prebuilt/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:/system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so

# Inherit from a11
$(call inherit-product, device/htc/a11/device.mk)

# Set those variables here to overwrite the inherited values.
PRODUCT_NAME := full_a11
PRODUCT_DEVICE := a11
PRODUCT_BRAND := HTC
PRODUCT_MANUFACTURER := HTC
PRODUCT_MODEL := a11
